# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MediaWiki
version:      1.05
version_from: lib/MediaWiki.pm
installdirs:  site
requires:
    Config::IniHash:               0
    Data::Dumper:                  0
    HTTP::Request::Common:         0
    LWP:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
